export const apiData = {
  success: true,
  statusCode: 201,
  message: 'products lists',
  data: {
    products: [
      {
        id: 1,
        product_name: 'Wireless Mouse',
        amount: 499,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 2,
        product_name: 'Bluetooth Keyboard',
        amount: 899,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 3,
        product_name: 'USB-C Cable',
        amount: 199,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 4,
        product_name: 'Laptop Stand',
        amount: 1299,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 5,
        product_name: 'Gaming Headset',
        amount: 1599,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 6,
        product_name: 'Smartphone Tripod',
        amount: 449,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 7,
        product_name: 'LED Monitor 24in',
        amount: 7999,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 8,
        product_name: 'Portable SSD 500GB',
        amount: 4499,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 9,
        product_name: 'Bluetooth Speaker',
        amount: 699,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 10,
        product_name: 'Wireless Charger',
        amount: 899,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 11,
        product_name: 'Noise Cancelling Earbuds',
        amount: 2199,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 12,
        product_name: 'USB Webcam',
        amount: 899,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 13,
        product_name: 'Mechanical Keyboard',
        amount: 2699,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 14,
        product_name: 'Gaming Mouse Pad XL',
        amount: 299,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 15,
        product_name: 'Smartwatch Basic',
        amount: 1999,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 16,
        product_name: '4K Action Camera',
        amount: 3499,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 17,
        product_name: 'VR Headset',
        amount: 5999,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 18,
        product_name: 'Wireless Earphones',
        amount: 999,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 19,
        product_name: 'Router AC1200',
        amount: 1299,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 20,
        product_name: 'RGB Light Strip',
        amount: 399,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 21,
        product_name: 'Power Bank 10000mAh',
        amount: 1299,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 22,
        product_name: 'HDMI Cable 4K',
        amount: 299,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 23,
        product_name: 'Laptop Cooler Pad',
        amount: 699,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 24,
        product_name: 'Smartphone Gimbal',
        amount: 2299,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 25,
        product_name: '128GB Memory Card',
        amount: 1299,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 26,
        product_name: 'Noise Soundbar',
        amount: 2499,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 27,
        product_name: 'Bluetooth Car Adapter',
        amount: 349,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 28,
        product_name: 'USB Hub 4-Port',
        amount: 499,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 29,
        product_name: 'Drone Mini',
        amount: 3999,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 30,
        product_name: 'LED Desk Lamp',
        amount: 599,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 31,
        product_name: 'Smart Plug',
        amount: 749,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 32,
        product_name: 'Smart Home Camera',
        amount: 1399,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 33,
        product_name: 'Mini Bluetooth Keyboard',
        amount: 699,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 34,
        product_name: 'Wired Earphones',
        amount: 149,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 35,
        product_name: 'Fitness Tracker Band',
        amount: 1499,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 36,
        product_name: 'Smart Door Lock',
        amount: 4999,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 37,
        product_name: 'Portable Bluetooth Keyboard',
        amount: 1799,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 38,
        product_name: 'Mobile Screen Guard Pack',
        amount: 199,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 39,
        product_name: 'Laptop Sleeve 15.6in',
        amount: 599,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 40,
        product_name: 'Digital Alarm Clock',
        amount: 349,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 41,
        product_name: 'Bluetooth Mouse Silent',
        amount: 649,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 42,
        product_name: 'USB Clip Microphone',
        amount: 499,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 43,
        product_name: 'Graphic Tablet Small',
        amount: 2399,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 44,
        product_name: 'TV Box 4K',
        amount: 2499,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 45,
        product_name: 'Keyboard Gel Cleaner',
        amount: 199,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 46,
        product_name: 'Electric Toothbrush',
        amount: 999,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 47,
        product_name: 'USB Rechargeable Fan',
        amount: 499,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 48,
        product_name: 'Mobile Ring Holder',
        amount: 99,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 49,
        product_name: 'Gaming Controller',
        amount: 1999,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 50,
        product_name: 'Mini Projector',
        amount: 3499,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 51,
        product_name: 'Wireless Security Alarm',
        amount: 899,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 52,
        product_name: 'Car Mobile Charger',
        amount: 299,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 53,
        product_name: 'Phone Case Silicone',
        amount: 199,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 54,
        product_name: 'Bluetooth Smart Scale',
        amount: 1599,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 55,
        product_name: 'Cordless Hair Trimmer',
        amount: 899,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 56,
        product_name: 'USB LED Light',
        amount: 99,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 57,
        product_name: 'Rechargeable Torch',
        amount: 299,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 58,
        product_name: 'USB Type-C OTG',
        amount: 129,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 59,
        product_name: 'Memory Foam Pillow',
        amount: 1199,
        image: 'httpsimages.pexels.com/photos/18105/pexels-photo.jpg',
      },
      {
        id: 60,
        product_name: 'Mini Table Fan',
        amount: 399,
        image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      },
    ],
  },
  timestamp: '2026-01-02T17:54:41.191Z',
};
